modLoader = "javafml"
loaderVersion = "[34,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheLMiffy1111/PackagedAvaritia/issues"

[[mods]]
	modId = "packagedavaritia"
	version = "0@VERSION@"
	displayName = "PackagedAvaritia"
	description = "A PackagedAuto addon that adds Avaritia autocrafting."
	logoFile = "packagedavaritia.logo.png"
	authors = "TheLMiffy1111"
	displayURL = "https://www.curseforge.com/minecraft/mc-mods/packagedavaritia"

[[dependencies.packagedexcrafting]]
	modId="forge"
	versionRange="[34,)"
	mandatory=true

[[dependencies.packagedexcrafting]]
	modId="packagedauto"
	versionRange="[2.0.5,)"
	mandatory=true

[[dependencies.packagedavaritia]]
	modId = "endless"
	versionRange = "[1.16.5-1,)"
	mandatory = true
